/* Generated By:JavaCC: Do not edit this line. JavaInterpreterConstants.java */
// =================================
//        IMPORTS
// =================================

package com.example.anny.myapplication;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaInterpreterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT_NUM = 5;
  /** RegularExpression Id. */
  int DOUBLE_NUM = 6;
  /** RegularExpression Id. */
  int SC = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int LPAREN = 9;
  /** RegularExpression Id. */
  int RPAREN = 10;
  /** RegularExpression Id. */
  int LARRAY = 11;
  /** RegularExpression Id. */
  int RARRAY = 12;
  /** RegularExpression Id. */
  int ASSIGN = 13;
  /** RegularExpression Id. */
  int NEW = 14;
  /** RegularExpression Id. */
  int TRUE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int BOOL_T = 17;
  /** RegularExpression Id. */
  int INT_T = 18;
  /** RegularExpression Id. */
  int DOUBLE_T = 19;
  /** RegularExpression Id. */
  int STRING_T = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int DOT = 22;
  /** RegularExpression Id. */
  int NAME = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<INT_NUM>",
    "<DOUBLE_NUM>",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"new\"",
    "\"true\"",
    "\"false\"",
    "\"bool\"",
    "\"int\"",
    "\"double\"",
    "\"string\"",
    "<STRING>",
    "\".\"",
    "<NAME>",
  };

}
